Fix build of inventor plugin under Clang in a non-Release build.
coin has a header include order problem - this workaround compensates
for it.  It caused build errors like this:
In file included from /usr/include/Inventor/SoDB.h:27:
/usr/include/Inventor/SbBasic.h:99:5: error: call to function 'cc_debugerror_post' that is neither visible in the template definition nor found by argument-dependent lookup
    cc_debugerror_post(funcname, "divide by zero error.", divider);
    ^

This fix is tested to build successfully with:
  inventor-dev 2.1.5-10-14ubuntu1
  libcoin60-dev 3.1.2-1
  libcoin40-dev 2.5.0-2
all on Ubuntu 10.04 x64